---
abstract: 'a legacy-code-friendly PSGI adapter for CGI::Application'
author:
  - 'Kazuho Oku <kazuhooku@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CGI::Application::Emulate::PSGI
name: CGI-Application-Emulate-PSGI
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
